config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  	root 'posts#index'

  	get '/signup' => 'users#new'
  	get '/login' => 'sessions#new'
  	post '/login' => 'sessions#create'
  	get '/logout' => 'sessions#destroy'

  	resources :users
  	resources :posts

    get 'search' => 'posts#search'
    

  	get '*unmatched_route', to: 'application#not_found'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  belongs_to :user

  def self.search(search)
  	if search
  		where(title: search).all
    else
    	all
  	end
  end
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	validates :username, presence: true, length: {minimum: 5}, uniqueness: true
	validates :password, length: { in: 6..20 }
	validates_email_format_of :email, :message => 'must be a valid email'
	validates :email, uniqueness: true

	has_many :posts
	has_many :topics

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def not_found
  	render_404
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

  private
  def render_404(exception = nil)
    if exception
        logger.info "Rendering 404: #{exception.message}"
    end

    render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :authorize

	def index
		@posts = Post.all
		
	end
	def search
		@search = params[:search]

		if @search.length > 0
			@posts = Post.where("title like ?", "%#{@search}%")
		else
			@posts = Post.all
		end
		render :partial => 'posts'
	end
	

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.user = current_user
		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])

	end

	def update
		@post = Post.find(params[:id])
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path
	end



	private

		def post_params
			params.require(:post).permit(:title, :body)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		
	end

	def create
		user = User.find_by_email(params[:email])
		if user && user.authenticate(params[:password])
      		session[:user_id] = user.id
      		redirect_to root_path
    	else
    		flash[:error] = "Email or password is incorrect"
    		redirect_to login_path
    	end
	end
	
	def destroy
		session[:user_id] = nil
		redirect_to login_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authorize, except: [:new, :create]
	def index
		@users = User.all
	end
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to posts_path
		else
			render 'new'
		end
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])

	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to user_path(@user)
		else
			render 'edit'
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to logout_path
	end


	private
		def user_params
			params.require(:user).permit(:username, :email, :password, :password_confirmation)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js' %>
  </head>

  <body style="background-color: #e6e6e6">
    
      <% if current_user %>
        <nav class="navbar navbar-inverse navbar-fixedtop">
              <div class="container">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <%= link_to "Forum", root_path, class: "navbar-brand" %>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                  <ul class="nav navbar-nav">
                    <li><%= link_to "Posts", posts_path %></li>
                    <li><%= link_to "Users", users_path%></li>
                  </ul>
                  <ul class="nav navbar-nav navbar-right">
                    <li><%= link_to "Create Post", new_post_path %></li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile
                      <span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li><%= link_to 'Your Posts', user_path(current_user.id)%></li>
                        <li><%= link_to 'Edit Info', edit_user_path(current_user.id)%></li>
                        <li><%= link_to 'Sign out', logout_path %></li>
                      </ul>
                    </li>
                  </ul>
                </div><!--/.nav-collapse -->
              </div>
            </nav>
      <% end %>
      <div class="container">
        <% if current_user %>
            Signed in as <%= current_user.username %> | <%= link_to "Logout", logout_path %>
            <br> <br>
        <% else %>
          <br>
          <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
          <br> <br>
        <% end %>
        <div class="well" style="background-color: white">
          <%= yield %>
        </div>
    </div>
    
  </body>
</html>

app/views/posts/_post_form.html.erb
<script type="text/javascript">
	CKEDITOR.replace('body')
</script>
<% if @post.errors.any? %>
	<div class="alert alert-danger">
		<ul>
			<% @post.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<%= form_for @post do |f| %>
	<h2>Title:</h2>
	<%= f.text_field :title, class: "form-control" %>
	<h2>Body:</h2>
	<%= f.cktext_area :body, class: "form-control", id: "body" %>
	<br>
	<%= f.submit "Submit", class: "btn btn-primary"%>
<% end %>

app/views/posts/_posts.html.erb
<% @posts.each do |post|%>
	<div class="well" id="<%= post.title %>">
		<h3><strong><%= link_to post.title, post_path(post.id) %> </strong></h3>
		<sub> by: <%= link_to post.user.username, user_path(post.user.id) %> </sub>
	</div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "post_form" %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<span>Search:</span>
<%= form_tag posts_path, remote: true do %>
  	<%= text_field_tag "search-bar", "" %> 
<% end %>

<br> <br>
<%= link_to 'New Post', new_post_path, class: "btn btn-primary" %> <br>
<br>
<div id="posts">
	<%= render 'posts' %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "post_form" %>

app/views/posts/show.html.erb
<div class="row" style="background-color: white">
	<div class="container">
		<h1><%= @post.title %></h1>
		<%= @post.body.html_safe %>
	</div>
	<br>
</div>
<br>
<strong><span>by: <%= link_to @post.user.username, user_path(@post.user.id) %> </span></strong>
<br> <br>

<% if @post.user.id == current_user.id %>
	<%= link_to "Delete Post", post_path(@post), method: :delete, class: "btn btn-primary" %>
	<span> </span>
	<%= link_to "Edit Post", edit_post_path(@post), class: "btn btn-primary" %>
<% end %>
<br>
<br>
<%= link_to "Back to Posts", posts_path, class: "btn btn-primary" %>

app/views/users/_user_form.html.erb
<% if @user.errors.any? %>
	<div class="alert alert-danger">
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<%= form_for @user, url: '/users' do |f| %>

  	Name: <%= f.text_field :username, class: "form-control"%> </br>
  	Email: <%= f.text_field :email, class: "form-control" %> </br>
  	Password: <%= f.password_field :password, class: "form-control" %> </br>
  	Password Confirmation: <%= f.password_field :password_confirmation, class: "form-control" %> </br>
  	<%= f.submit "Submit" , class: "btn btn-primary"%>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>
<%= render 'user_form' %>

app/views/users/index.html.erb
<h1>Users</h1>

<% @users.each do |user|%>
	<div class="well">
		<h3><strong><%= link_to user.username, user_path(user.id) %> </strong></h3>
	</div>
<% end %>

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= render 'user_form' %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<% @user.posts.each do |post| %>
	<div class="well">
		<h3><strong><%= link_to post.title, post_path(post.id) %> </strong></h3>
	</div>
<% end %>